### PR TITLE
Löschen von Posts via Passwort

### PR DESCRIPTION
**Pull request by stefanluth**

### CODE REVIEW

**Review by Jeremy-Hill-02 — DISMISSED** [review]
Vielleicht eine kleine Beschreibung in die Readme, wie das anwendbar ist.

**Comment by stefanluth** [comment]
@Jeremy-Hill-02 findest du das mit dem Cookie in Ordnung? Finde das bisschen sus :D

**Comment by Jeremy-Hill-02** [comment]
> @Jeremy-Hill-02 findest du das mit dem Cookie in Ordnung? Finde das bisschen sus :D

Ja schon ein bisschen sus. Vielleicht machen wir wirklich eine admin page, die dann wiederum mit einem bestimmten Passwort gesichert ist?

**Comment by Jeremy-Hill-02** [comment]
Ich lass das mal hier:

No, it is not considered a good practice to retrieve passwords from request cookies. Cookies are typically used for session management and storing small amounts of non-sensitive data. Storing passwords in cookies can introduce security risks and should be avoided.

Here's why it is not recommended:

- Cookie security: Cookies are vulnerable to attacks such as cross-site scripting (XSS) and cross-site request forgery (CSRF). If a malicious user gains access to the cookie containing the password, they can easily impersonate the user and potentially compromise their account.

- Exposure in transit: Cookies are transmitted with each HTTP request, including potentially over insecure networks. This means that the password would be visible in plaintext during transit, making it susceptible to interception.

- Persistent storage: Cookies are typically stored on the client-side and may persist beyond the session duration. Storing passwords in cookies would expose them to being accessed by unauthorized users if the cookie is stolen or shared.

Instead of retrieving passwords from cookies, consider the following:

- Session management: Use cookies to store a session identifier or token that can be used to associate the user with their session on the server-side. The actual password should never be stored in the cookie.

- Token-based authentication: Implement token-based authentication mechanisms, such as JSON Web Tokens (JWT), where the token is securely stored in a cookie or authorization header. This allows the server to authenticate the user without exposing the password.

- Password hashing and comparison: Store password hashes securely on the server-side, as mentioned earlier. When authenticating the user, compare the hashed password stored in the database with the hashed version of the password received in the request. If they match, authentication is successful.

Remember, security best practices recommend not storing passwords or sensitive information in cookies or any client-side storage. Instead, focus on secure server-side storage, strong authentication mechanisms, and secure communication channels.

**Comment by stefanluth** [comment]
Auf der andere Seite wiederum werden die Passwörter täglich erneuert.

**Pull request closed without merging**
